import os


save_folder = '/mnt/ssd/khoadv/Backup/visualize'
draw_bb_config = {
    'BDD_BDD_layer_features_seperate_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'BDD',
        'metric_results_path': None,
        'layers_to_store': ['transformer.encoder.layers.4.dropout3', 'transformer.encoder.layers.5.self_attn.output_proj'],
        'layers_config': {},
    },
    'OpenImages_BDD_layer_features_seperate_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['transformer.encoder.layers.4.dropout3', 'transformer.encoder.layers.5.self_attn.output_proj'],
        'layers_config': {},
    },
    'COCO_BDD_layer_features_seperate_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['transformer.encoder.layers.4.dropout3', 'transformer.encoder.layers.5.self_attn.output_proj'],
        'layers_config': {},
    },
    'BDD_BDD_combined_one_cnn_layer_features_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'BDD',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    'OpenImages_BDD_combined_one_cnn_layer_features_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    'COCO_BDD_combined_one_cnn_layer_features_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    
    
    
    'VOC_VOC_layer_features_seperate_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'VOC',
        'metric_results_path': None,
        'layers_to_store': ['transformer.encoder.layers.4.dropout3', 'transformer.encoder.layers.5.self_attn.output_proj'],
        'layers_config': {},
    },
    'OpenImages_VOC_layer_features_seperate_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['transformer.encoder.layers.4.dropout3', 'transformer.encoder.layers.5.self_attn.output_proj'],
        'layers_config': {},
    },
    'COCO_VOC_layer_features_seperate_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['transformer.encoder.layers.4.dropout3', 'transformer.encoder.layers.5.self_attn.output_proj'],
        'layers_config': {},
    },
    'VOC_VOC_combined_one_cnn_layer_features_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'VOC',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    'OpenImages_VOC_combined_one_cnn_layer_features_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    'COCO_VOC_combined_one_cnn_layer_features_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.self_attn.output_proj', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.self_attn.output_proj',
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    
    
    
    'VOC_VOC_COCO_layer_features_seperate_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'VOC',
        'OOD_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample', 'transformer.encoder.layers.2.dropout3', 'transformer.encoder.layers.3.dropout3', 'transformer.encoder.layers.4.dropout3'],
        'layers_config': {},
    },
    'VOC_VOC_OpenImages_layer_features_seperate_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'VOC',
        'OOD_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample', 'transformer.encoder.layers.2.dropout3', 'transformer.encoder.layers.3.dropout3', 'transformer.encoder.layers.4.dropout3'],
        'layers_config': {},
    },
    'OpenImages_VOC_layer_features_seperate_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample', 'transformer.encoder.layers.2.dropout3', 'transformer.encoder.layers.3.dropout3', 'transformer.encoder.layers.4.dropout3'],
        'layers_config': {},
    },
    'COCO_VOC_layer_features_seperate_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample', 'transformer.encoder.layers.2.dropout3', 'transformer.encoder.layers.3.dropout3', 'transformer.encoder.layers.4.dropout3'],
        'layers_config': {},
    },
    'VOC_VOC_COCO_combined_one_cnn_layer_features_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'VOC',
        'OOD_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    'VOC_VOC_OpenImages_combined_one_cnn_layer_features_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'VOC',
        'OOD_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    'OpenImages_VOC_combined_one_cnn_layer_features_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'OpenImages',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
    'COCO_VOC_combined_one_cnn_layer_features_reverse_po_ne_0': {
        'tdset': None,
        'id_dataset': None,
        'draw_dataset': 'COCO',
        'metric_results_path': None,
        'layers_to_store': ['backbone.0.body.layer4.0.downsample_transformer.encoder.layers.1.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.2.dropout3', 
                            'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.3.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.4.dropout3', 'backbone.0.body.layer4.0.downsample_transformer.encoder.layers.5.dropout3'],
        'layers_config': {},
    },
}