import os
from itertools import combinations


# NUM_LAYERS = {
#         "vitdet_b": 12,
#         "vitdet_l": 24,
#         "vitdet_h": 32
# }

# n_layers = NUM_LAYERS['vitdet_b']

# hook_names = []
# for i in range(n_layers):
#     hook_names += [f'backbone.net.blocks.{i}.norm1_in', f'backbone.net.blocks.{i}.norm1_out'] 
#     hook_names += [f'backbone.net.blocks.{i}.attn.qkv_in', f'backbone.net.blocks.{i}.attn.qkv_out'] 
#     hook_names += [f'backbone.net.blocks.{i}.attn.proj_in', f'backbone.net.blocks.{i}.attn.proj_out'] 
#     hook_names += [f'backbone.net.blocks.{i}.norm2_in', f'backbone.net.blocks.{i}.norm2_out'] 
#     hook_names += [f'backbone.net.blocks.{i}.mlp.fc1_in', f'backbone.net.blocks.{i}.mlp.fc1_out'] 
#     hook_names += [f'backbone.net.blocks.{i}.mlp.act_in', f'backbone.net.blocks.{i}.mlp.act_out'] 
#     hook_names += [f'backbone.net.blocks.{i}.mlp.norm_in', f'backbone.net.blocks.{i}.mlp.norm_out'] 
#     hook_names += [f'backbone.net.blocks.{i}.mlp.fc2_in', f'backbone.net.blocks.{i}.mlp.fc2_out'] 
        

hook_names = [
    'backbone.net.blocks.0.attn.proj_in',
    'backbone.net.blocks.0.attn.proj_out',
    'backbone.net.blocks.0.attn.qkv_in',
    'backbone.net.blocks.0.attn.qkv_out',
    'backbone.net.blocks.0.mlp.act_in',
    'backbone.net.blocks.0.mlp.act_out',
    'backbone.net.blocks.0.mlp.fc1_in',
    'backbone.net.blocks.0.mlp.fc1_out',
    'backbone.net.blocks.0.mlp.fc2_in',
    'backbone.net.blocks.0.mlp.fc2_out',
    'backbone.net.blocks.0.mlp.norm_in',
    'backbone.net.blocks.0.mlp.norm_out',
    'backbone.net.blocks.0.norm1_in',
    'backbone.net.blocks.0.norm1_out',
    'backbone.net.blocks.0.norm2_in',
    'backbone.net.blocks.0.norm2_out',
    'backbone.net.blocks.1.attn.proj_in',
    'backbone.net.blocks.1.attn.proj_out',
    'backbone.net.blocks.1.attn.qkv_in',
    'backbone.net.blocks.1.attn.qkv_out',
    'backbone.net.blocks.1.mlp.act_in',
    'backbone.net.blocks.1.mlp.act_out',
    'backbone.net.blocks.1.mlp.fc1_in',
    'backbone.net.blocks.1.mlp.fc1_out',
    'backbone.net.blocks.1.mlp.fc2_in',
    'backbone.net.blocks.1.mlp.fc2_out',
    'backbone.net.blocks.1.mlp.norm_in',
    'backbone.net.blocks.1.mlp.norm_out',
    'backbone.net.blocks.1.norm1_in',
    'backbone.net.blocks.1.norm1_out',
    'backbone.net.blocks.1.norm2_in',
    'backbone.net.blocks.1.norm2_out',
    'backbone.net.blocks.10.attn.proj_in',
    'backbone.net.blocks.10.attn.proj_out',
    'backbone.net.blocks.10.attn.qkv_in',
    'backbone.net.blocks.10.attn.qkv_out',
    'backbone.net.blocks.10.mlp.act_in',
    'backbone.net.blocks.10.mlp.act_out',
    'backbone.net.blocks.10.mlp.fc1_in',
    'backbone.net.blocks.10.mlp.fc1_out',
    'backbone.net.blocks.10.mlp.fc2_in',
    'backbone.net.blocks.10.mlp.fc2_out',
    'backbone.net.blocks.10.mlp.norm_in',
    'backbone.net.blocks.10.mlp.norm_out',
    'backbone.net.blocks.10.norm1_in',
    'backbone.net.blocks.10.norm1_out',
    'backbone.net.blocks.10.norm2_in',
    'backbone.net.blocks.10.norm2_out',
    'backbone.net.blocks.11.attn.proj_in',
    'backbone.net.blocks.11.attn.proj_out',
    'backbone.net.blocks.11.attn.qkv_in',
    'backbone.net.blocks.11.attn.qkv_out',
    'backbone.net.blocks.11.mlp.act_in',
    'backbone.net.blocks.11.mlp.act_out',
    'backbone.net.blocks.11.mlp.fc1_in',
    'backbone.net.blocks.11.mlp.fc1_out',
    'backbone.net.blocks.11.mlp.fc2_in',
    'backbone.net.blocks.11.mlp.fc2_out',
    'backbone.net.blocks.11.mlp.norm_in',
    'backbone.net.blocks.11.mlp.norm_out',
    'backbone.net.blocks.11.norm1_in',
    'backbone.net.blocks.11.norm1_out',
    'backbone.net.blocks.11.norm2_in',
    'backbone.net.blocks.11.norm2_out',
    'backbone.net.blocks.2.attn.proj_in',
    'backbone.net.blocks.2.attn.proj_out',
    'backbone.net.blocks.2.attn.qkv_in',
    'backbone.net.blocks.2.attn.qkv_out',
    'backbone.net.blocks.2.mlp.act_in',
    'backbone.net.blocks.2.mlp.act_out',
    'backbone.net.blocks.2.mlp.fc1_in',
    'backbone.net.blocks.2.mlp.fc1_out',
    'backbone.net.blocks.2.mlp.fc2_in',
    'backbone.net.blocks.2.mlp.fc2_out',
    'backbone.net.blocks.2.mlp.norm_in',
    'backbone.net.blocks.2.mlp.norm_out',
    'backbone.net.blocks.2.norm1_in',
    'backbone.net.blocks.2.norm1_out',
    'backbone.net.blocks.2.norm2_in',
    'backbone.net.blocks.2.norm2_out',
    'backbone.net.blocks.3.attn.proj_in',
    'backbone.net.blocks.3.attn.proj_out',
    'backbone.net.blocks.3.attn.qkv_in',
    'backbone.net.blocks.3.attn.qkv_out',
    'backbone.net.blocks.3.mlp.act_in',
    'backbone.net.blocks.3.mlp.act_out',
    'backbone.net.blocks.3.mlp.fc1_in',
    'backbone.net.blocks.3.mlp.fc1_out',
    'backbone.net.blocks.3.mlp.fc2_in',
    'backbone.net.blocks.3.mlp.fc2_out',
    'backbone.net.blocks.3.mlp.norm_in',
    'backbone.net.blocks.3.mlp.norm_out',
    'backbone.net.blocks.3.norm1_in',
    'backbone.net.blocks.3.norm1_out',
    'backbone.net.blocks.3.norm2_in',
    'backbone.net.blocks.3.norm2_out',
    'backbone.net.blocks.4.attn.proj_in',
    'backbone.net.blocks.4.attn.proj_out',
    'backbone.net.blocks.4.attn.qkv_in',
    'backbone.net.blocks.4.attn.qkv_out',
    'backbone.net.blocks.4.mlp.act_in',
    'backbone.net.blocks.4.mlp.act_out',
    'backbone.net.blocks.4.mlp.fc1_in',
    'backbone.net.blocks.4.mlp.fc1_out',
    'backbone.net.blocks.4.mlp.fc2_in',
    'backbone.net.blocks.4.mlp.fc2_out',
    'backbone.net.blocks.4.mlp.norm_in',
    'backbone.net.blocks.4.mlp.norm_out',
    'backbone.net.blocks.4.norm1_in',
    'backbone.net.blocks.4.norm1_out',
    'backbone.net.blocks.4.norm2_in',
    'backbone.net.blocks.4.norm2_out',
    'backbone.net.blocks.5.attn.proj_in',
    'backbone.net.blocks.5.attn.proj_out',
    'backbone.net.blocks.5.attn.qkv_in',
    'backbone.net.blocks.5.attn.qkv_out',
    'backbone.net.blocks.5.mlp.act_in',
    'backbone.net.blocks.5.mlp.act_out',
    'backbone.net.blocks.5.mlp.fc1_in',
    'backbone.net.blocks.5.mlp.fc1_out',
    'backbone.net.blocks.5.mlp.fc2_in',
    'backbone.net.blocks.5.mlp.fc2_out',
    'backbone.net.blocks.5.mlp.norm_in',
    'backbone.net.blocks.5.mlp.norm_out',
    'backbone.net.blocks.5.norm1_in',
    'backbone.net.blocks.5.norm1_out',
    'backbone.net.blocks.5.norm2_in',
    'backbone.net.blocks.5.norm2_out',
    'backbone.net.blocks.6.attn.proj_in',
    'backbone.net.blocks.6.attn.proj_out',
    'backbone.net.blocks.6.attn.qkv_in',
    'backbone.net.blocks.6.attn.qkv_out',
    'backbone.net.blocks.6.mlp.act_in',
    'backbone.net.blocks.6.mlp.act_out',
    'backbone.net.blocks.6.mlp.fc1_in',
    'backbone.net.blocks.6.mlp.fc1_out',
    'backbone.net.blocks.6.mlp.fc2_in',
    'backbone.net.blocks.6.mlp.fc2_out',
    'backbone.net.blocks.6.mlp.norm_in',
    'backbone.net.blocks.6.mlp.norm_out',
    'backbone.net.blocks.6.norm1_in',
    'backbone.net.blocks.6.norm1_out',
    'backbone.net.blocks.6.norm2_in',
    'backbone.net.blocks.6.norm2_out',
    'backbone.net.blocks.7.attn.proj_in',
    'backbone.net.blocks.7.attn.proj_out',
    'backbone.net.blocks.7.attn.qkv_in',
    'backbone.net.blocks.7.attn.qkv_out',
    'backbone.net.blocks.7.mlp.act_in',
    'backbone.net.blocks.7.mlp.act_out',
    'backbone.net.blocks.7.mlp.fc1_in',
    'backbone.net.blocks.7.mlp.fc1_out',
    'backbone.net.blocks.7.mlp.fc2_in',
    'backbone.net.blocks.7.mlp.fc2_out',
    'backbone.net.blocks.7.mlp.norm_in',
    'backbone.net.blocks.7.mlp.norm_out',
    'backbone.net.blocks.7.norm1_in',
    'backbone.net.blocks.7.norm1_out',
    'backbone.net.blocks.7.norm2_in',
    'backbone.net.blocks.7.norm2_out',
    'backbone.net.blocks.8.attn.proj_in',
    'backbone.net.blocks.8.attn.proj_out',
    'backbone.net.blocks.8.attn.qkv_in',
    'backbone.net.blocks.8.attn.qkv_out',
    'backbone.net.blocks.8.mlp.act_in',
    'backbone.net.blocks.8.mlp.act_out',
    'backbone.net.blocks.8.mlp.fc1_in',
    'backbone.net.blocks.8.mlp.fc1_out',
    'backbone.net.blocks.8.mlp.fc2_in',
    'backbone.net.blocks.8.mlp.fc2_out',
    'backbone.net.blocks.8.mlp.norm_in',
    'backbone.net.blocks.8.mlp.norm_out',
    'backbone.net.blocks.8.norm1_in',
    'backbone.net.blocks.8.norm1_out',
    'backbone.net.blocks.8.norm2_in',
    'backbone.net.blocks.8.norm2_out',
    'backbone.net.blocks.9.attn.proj_in',
    'backbone.net.blocks.9.attn.proj_out',
    'backbone.net.blocks.9.attn.qkv_in',
    'backbone.net.blocks.9.attn.qkv_out',
    'backbone.net.blocks.9.mlp.act_in',
    'backbone.net.blocks.9.mlp.act_out',
    'backbone.net.blocks.9.mlp.fc1_in',
    'backbone.net.blocks.9.mlp.fc1_out',
    'backbone.net.blocks.9.mlp.fc2_in',
    'backbone.net.blocks.9.mlp.fc2_out',
    'backbone.net.blocks.9.mlp.norm_in',
    'backbone.net.blocks.9.mlp.norm_out',
    'backbone.net.blocks.9.norm1_in',
    'backbone.net.blocks.9.norm1_out',
    'backbone.net.blocks.9.norm2_in',
    'backbone.net.blocks.9.norm2_out',
    'backbone.simfp_2.0_in',
    'backbone.simfp_2.0_out',
    'backbone.simfp_2.1_in',
    'backbone.simfp_2.1_out',
    'backbone.simfp_2.2_in',
    'backbone.simfp_2.2_out',
    'backbone.simfp_2.3_in',
    'backbone.simfp_2.3_out',
    'backbone.simfp_2.4.norm_in',
    'backbone.simfp_2.4.norm_out',
    'backbone.simfp_2.4_in',
    'backbone.simfp_2.4_out',
    'backbone.simfp_2.5.norm_in',
    'backbone.simfp_2.5.norm_out',
    'backbone.simfp_2.5_in',
    'backbone.simfp_2.5_out',
    'backbone.simfp_3.0_in',
    'backbone.simfp_3.0_out',
    'backbone.simfp_3.1.norm_in',
    'backbone.simfp_3.1.norm_out',
    'backbone.simfp_3.1_in',
    'backbone.simfp_3.1_out',
    'backbone.simfp_3.2.norm_in',
    'backbone.simfp_3.2.norm_out',
    'backbone.simfp_3.2_in',
    'backbone.simfp_3.2_out',
    'backbone.simfp_4.0.norm_in',
    'backbone.simfp_4.0.norm_out',
    'backbone.simfp_4.0_in',
    'backbone.simfp_4.0_out',
    'backbone.simfp_4.1.norm_in',
    'backbone.simfp_4.1.norm_out',
    'backbone.simfp_4.1_in',
    'backbone.simfp_4.1_out',
    'backbone.simfp_5.0_in',
    'backbone.simfp_5.0_out',
    'backbone.simfp_5.1.norm_in',
    'backbone.simfp_5.1.norm_out',
    'backbone.simfp_5.1_in',
    'backbone.simfp_5.1_out',
    'backbone.simfp_5.2.norm_in',
    'backbone.simfp_5.2.norm_out',
    'backbone.simfp_5.2_in',
    'backbone.simfp_5.2_out',
    'box_features'
    ]

        
if __name__ == '__main__':
    pass
    